// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqX9mFeVlBTPO3Hv9EjBYgiC8w4StOv1s',
    appId: '1:788709527048:web:29fb7848eeaad34932cbbd',
    messagingSenderId: '788709527048',
    projectId: 'waqti-bfc00',
    authDomain: 'waqti-bfc00.firebaseapp.com',
    storageBucket: 'waqti-bfc00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp0Hrra7pAREJ-_iG6lMKtKEEOIz5BCq0',
    appId: '1:788709527048:android:67d67d10b478c76a32cbbd',
    messagingSenderId: '788709527048',
    projectId: 'waqti-bfc00',
    storageBucket: 'waqti-bfc00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD32kXyyiy0BUgF3Ywd9c3u3E8mg0nj4_g',
    appId: '1:788709527048:ios:83f9a3edb9eb3c6e32cbbd',
    messagingSenderId: '788709527048',
    projectId: 'waqti-bfc00',
    storageBucket: 'waqti-bfc00.appspot.com',
    iosBundleId: 'com.example.waqti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD32kXyyiy0BUgF3Ywd9c3u3E8mg0nj4_g',
    appId: '1:788709527048:ios:83f9a3edb9eb3c6e32cbbd',
    messagingSenderId: '788709527048',
    projectId: 'waqti-bfc00',
    storageBucket: 'waqti-bfc00.appspot.com',
    iosBundleId: 'com.example.waqti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqX9mFeVlBTPO3Hv9EjBYgiC8w4StOv1s',
    appId: '1:788709527048:web:41acca714f54645432cbbd',
    messagingSenderId: '788709527048',
    projectId: 'waqti-bfc00',
    authDomain: 'waqti-bfc00.firebaseapp.com',
    storageBucket: 'waqti-bfc00.appspot.com',
  );
}
